//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landmarks.Common.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Landmarks.Common.Resources.Admin.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a classification of landmarks. It is used in this website as well as in database.. This classification is specifically adjusted to Bulgarian situtation. In a case of other countries there would be needed corrections in composition of categories.In a case of other countries there would be needed a thorough work at adjustments of border conditions for landmarks..
        /// </summary>
        public static string descCategory {
            get {
                return ResourceManager.GetString("descCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria is a land with rich history and traditions. There are many historical landmarks scattered all over the country and dating back to ancient times, the Middle Ages, the recent past socialist period and up to nowadays modern times..
        /// </summary>
        public static string descLandmark {
            get {
                return ResourceManager.GetString("descLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provinces of Bulgaria are the first level administrative subdivisions of the country.Since 1999, Bulgaria has been divided into 28 provinces which correspond approximately to the 28 districts that existed before 1987..
        /// </summary>
        public static string descRegion {
            get {
                return ResourceManager.GetString("descRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lblActions {
            get {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string lblAddCategory {
            get {
                return ResourceManager.GetString("lblAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Landmark.
        /// </summary>
        public static string lblAddLandmark {
            get {
                return ResourceManager.GetString("lblAddLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Region.
        /// </summary>
        public static string lblAddRegion {
            get {
                return ResourceManager.GetString("lblAddRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string lblAllCategory {
            get {
                return ResourceManager.GetString("lblAllCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Landmarks.
        /// </summary>
        public static string lblAllLandmarks {
            get {
                return ResourceManager.GetString("lblAllLandmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Regions.
        /// </summary>
        public static string lblAllRegions {
            get {
                return ResourceManager.GetString("lblAllRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category namee.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        public static string lblPopulation {
            get {
                return ResourceManager.GetString("lblPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name.
        /// </summary>
        public static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark category list.
        /// </summary>
        public static string titleCategory {
            get {
                return ResourceManager.GetString("titleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmarks list.
        /// </summary>
        public static string titleLandmark {
            get {
                return ResourceManager.GetString("titleLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian regions.
        /// </summary>
        public static string titleRegion {
            get {
                return ResourceManager.GetString("titleRegion", resourceCulture);
            }
        }
    }
}
